services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/app"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    # depends_on:
    #   - backend
